# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 73ad5e405a996d6c56c5bc2c217963edf306caa2510aaf1e92928b2c4b6e92b158df6b4ccdf27109912600eba976843704e41ccb57d78faf30d3b52cded69c2f

test:
  secret_key_base: 4d2cef00d757250b2290149aa58ca1c0f5b1094a372a38d5b6a1ba06640a024006a7ba2669cc61ccc37666002ab6a8d734e451cdb392e7597f2c20494b063890

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
